Person.create(name: 'Luke Skywalker', height: '172', mass: '77', hair_color: 'blond', skin_color: 'fair', eye_color: 'blue', birth_year: '19BBY', gender: 'male', homeworld_id: 1, id: 1)
Person.create(name: 'C-3PO', height: '167', mass: '75', hair_color: 'n/a', skin_color: 'gold', eye_color: 'yellow', birth_year: '112BBY', gender: 'n/a', homeworld_id: 1, id: 2)
Person.create(name: 'R2-D2', height: '96', mass: '32', hair_color: 'n/a', skin_color: 'white, blue', eye_color: 'red', birth_year: '33BBY', gender: 'n/a', homeworld_id: 8, id: 3)
Person.create(name: 'Darth Vader', height: '202', mass: '136', hair_color: 'none', skin_color: 'white', eye_color: 'yellow', birth_year: '41.9BBY', gender: 'male', homeworld_id: 1, id: 4)
Person.create(name: 'Leia Organa', height: '150', mass: '49', hair_color: 'brown', skin_color: 'light', eye_color: 'brown', birth_year: '19BBY', gender: 'female', homeworld_id: 2, id: 5)
Person.create(name: 'Owen Lars', height: '178', mass: '120', hair_color: 'brown, grey', skin_color: 'light', eye_color: 'blue', birth_year: '52BBY', gender: 'male', homeworld_id: 1, id: 6)
Person.create(name: 'Beru Whitesun lars', height: '165', mass: '75', hair_color: 'brown', skin_color: 'light', eye_color: 'blue', birth_year: '47BBY', gender: 'female', homeworld_id: 1, id: 7)
Person.create(name: 'R5-D4', height: '97', mass: '32', hair_color: 'n/a', skin_color: 'white, red', eye_color: 'red', birth_year: 'unknown', gender: 'n/a', homeworld_id: 1, id: 8)
Person.create(name: 'Biggs Darklighter', height: '183', mass: '84', hair_color: 'black', skin_color: 'light', eye_color: 'brown', birth_year: '24BBY', gender: 'male', homeworld_id: 1, id: 9)
Person.create(name: 'Obi-Wan Kenobi', height: '182', mass: '77', hair_color: 'auburn, white', skin_color: 'fair', eye_color: 'blue-gray', birth_year: '57BBY', gender: 'male', homeworld_id: 20, id: 10)
Person.create(name: 'Anakin Skywalker', height: '188', mass: '84', hair_color: 'blond', skin_color: 'fair', eye_color: 'blue', birth_year: '41.9BBY', gender: 'male', homeworld_id: 1, id: 11)
Person.create(name: 'Wilhuff Tarkin', height: '180', mass: 'unknown', hair_color: 'auburn, grey', skin_color: 'fair', eye_color: 'blue', birth_year: '64BBY', gender: 'male', homeworld_id: 21, id: 12)
Person.create(name: 'Chewbacca', height: '228', mass: '112', hair_color: 'brown', skin_color: 'unknown', eye_color: 'blue', birth_year: '200BBY', gender: 'male', homeworld_id: 14, id: 13)
Person.create(name: 'Han Solo', height: '180', mass: '80', hair_color: 'brown', skin_color: 'fair', eye_color: 'brown', birth_year: '29BBY', gender: 'male', homeworld_id: 22, id: 14)
Person.create(name: 'Greedo', height: '173', mass: '74', hair_color: 'n/a', skin_color: 'green', eye_color: 'black', birth_year: '44BBY', gender: 'male', homeworld_id: 23, id: 15)
Person.create(name: 'Jabba Desilijic Tiure', height: '175', mass: '1,358', hair_color: 'n/a', skin_color: 'green-tan, brown', eye_color: 'orange', birth_year: '600BBY', gender: 'hermaphrodite', homeworld_id: 24, id: 16)
Person.create(name: 'Wedge Antilles', height: '170', mass: '77', hair_color: 'brown', skin_color: 'fair', eye_color: 'hazel', birth_year: '21BBY', gender: 'male', homeworld_id: 22, id: 18)
Person.create(name: 'Jek Tono Porkins', height: '180', mass: '110', hair_color: 'brown', skin_color: 'fair', eye_color: 'blue', birth_year: 'unknown', gender: 'male', homeworld_id: 26, id: 19)
Person.create(name: 'Yoda', height: '66', mass: '17', hair_color: 'white', skin_color: 'green', eye_color: 'brown', birth_year: '896BBY', gender: 'male', homeworld_id: 28, id: 20)
Person.create(name: 'Palpatine', height: '170', mass: '75', hair_color: 'grey', skin_color: 'pale', eye_color: 'yellow', birth_year: '82BBY', gender: 'male', homeworld_id: 8, id: 21)
Person.create(name: 'Boba Fett', height: '183', mass: '78.2', hair_color: 'black', skin_color: 'fair', eye_color: 'brown', birth_year: '31.5BBY', gender: 'male', homeworld_id: 10, id: 22)
Person.create(name: 'IG-88', height: '200', mass: '140', hair_color: 'none', skin_color: 'metal', eye_color: 'red', birth_year: '15BBY', gender: 'none', homeworld_id: 28, id: 23)
Person.create(name: 'Bossk', height: '190', mass: '113', hair_color: 'none', skin_color: 'green', eye_color: 'red', birth_year: '53BBY', gender: 'male', homeworld_id: 29, id: 24)
Person.create(name: 'Lando Calrissian', height: '177', mass: '79', hair_color: 'black', skin_color: 'dark', eye_color: 'brown', birth_year: '31BBY', gender: 'male', homeworld_id: 30, id: 25)
Person.create(name: 'Lobot', height: '175', mass: '79', hair_color: 'none', skin_color: 'light', eye_color: 'blue', birth_year: '37BBY', gender: 'male', homeworld_id: 6, id: 26)
Person.create(name: 'Ackbar', height: '180', mass: '83', hair_color: 'none', skin_color: 'brown mottle', eye_color: 'orange', birth_year: '41BBY', gender: 'male', homeworld_id: 31, id: 27)
Person.create(name: 'Mon Mothma', height: '150', mass: 'unknown', hair_color: 'auburn', skin_color: 'fair', eye_color: 'blue', birth_year: '48BBY', gender: 'female', homeworld_id: 32, id: 28)
Person.create(name: 'Arvel Crynyd', height: 'unknown', mass: 'unknown', hair_color: 'brown', skin_color: 'fair', eye_color: 'brown', birth_year: 'unknown', gender: 'male', homeworld_id: 28, id: 29)

Person.create(name: 'Wicket Systri Warrick', height: '88', mass: '20', hair_color: 'brown', skin_color: 'brown', eye_color: 'brown', birth_year: '8BBY', gender: 'male', homeworld_id: 7, id: 30)
Person.create(name: 'Nien Nunb', height: '160', mass: '68', hair_color: 'none', skin_color: 'grey', eye_color: 'black', birth_year: 'unknown', gender: 'male', homeworld_id: 33, id: 31)
Person.create(name: 'Qui-Gon Jinn', height: '193', mass: '89', hair_color: 'brown', skin_color: 'fair', eye_color: 'blue', birth_year: '92BBY', gender: 'male', homeworld_id: 28, id: 32)
Person.create(name: 'Nute Gunray', height: '191', mass: '90', hair_color: 'none', skin_color: 'mottled green', eye_color: 'red', birth_year: 'unknown', gender: 'male', homeworld_id: 18, id: 33)
Person.create(name: 'Finis Valorum', height: '170', mass: 'unknown', hair_color: 'blond', skin_color: 'fair', eye_color: 'blue', birth_year: '91BBY', gender: 'male', homeworld_id: 9, id: 34)
Person.create(name: 'Padmé Amidala', height: '185', mass: '45', hair_color: 'brown', skin_color: 'light', eye_color: 'brown', birth_year: '46BBY', gender: 'female', homeworld_id: 8, id: 35)
Person.create(name: 'Jar Jar Binks', height: '196', mass: '66', hair_color: 'none', skin_color: 'orange', eye_color: 'orange', birth_year: '52BBY', gender: 'male', homeworld_id: 8, id: 36)
Person.create(name: 'Roos Tarpals', height: '224', mass: '82', hair_color: 'none', skin_color: 'grey', eye_color: 'orange', birth_year: 'unknown', gender: 'male', homeworld_id: 8, id: 37)
Person.create(name: 'Rugor Nass', height: '206', mass: 'unknown', hair_color: 'none', skin_color: 'green', eye_color: 'orange', birth_year: 'unknown', gender: 'male', homeworld_id: 8, id: 38)
Person.create(name: 'Ric Olié', height: '183', mass: 'unknown', hair_color: 'brown', skin_color: 'fair', eye_color: 'blue', birth_year: 'unknown', gender: 'male', homeworld_id: 8, id: 39)
Person.create(name: 'Watto', height: '137', mass: 'unknown', hair_color: 'black', skin_color: 'blue, grey', eye_color: 'yellow', birth_year: 'unknown', gender: 'male', homeworld_id: 34, id: 40)
Person.create(name: 'Sebulba', height: '112', mass: '40', hair_color: 'none', skin_color: 'grey, red', eye_color: 'orange', birth_year: 'unknown', gender: 'male', homeworld_id: 35, id: 41)
Person.create(name: 'Quarsh Panaka', height: '183', mass: 'unknown', hair_color: 'black', skin_color: 'dark', eye_color: 'brown', birth_year: '62BBY', gender: 'male', homeworld_id: 8, id: 42)
Person.create(name: 'Shmi Skywalker', height: '163', mass: 'unknown', hair_color: 'black', skin_color: 'fair', eye_color: 'brown', birth_year: '72BBY', gender: 'female', homeworld_id: 1, id: 43)
Person.create(name: 'Darth Maul', height: '175', mass: '80', hair_color: 'none', skin_color: 'red', eye_color: 'yellow', birth_year: '54BBY', gender: 'male', homeworld_id: 36, id: 44)
Person.create(name: 'Bib Fortuna', height: '180', mass: 'unknown', hair_color: 'none', skin_color: 'pale', eye_color: 'pink', birth_year: 'unknown', gender: 'male', homeworld_id: 37, id: 45)
Person.create(name: 'Ayla Secura', height: '178', mass: '55', hair_color: 'none', skin_color: 'blue', eye_color: 'hazel', birth_year: '48BBY', gender: 'female', homeworld_id: 37, id: 46)
Person.create(name: 'Ratts Tyerel', height: '79', mass: '15', hair_color: 'none', skin_color: 'grey, blue', eye_color: 'unknown', birth_year: 'unknown', gender: 'male', homeworld_id: 38, id: 47)
Person.create(name: 'Dud Bolt', height: '94', mass: '45', hair_color: 'none', skin_color: 'blue, grey', eye_color: 'yellow', birth_year: 'unknown', gender: 'male', homeworld_id: 39, id: 48)
Person.create(name: 'Gasgano', height: '122', mass: 'unknown', hair_color: 'none', skin_color: 'white, blue', eye_color: 'black', birth_year: 'unknown', gender: 'male', homeworld_id: 40, id: 49)
Person.create(name: 'Ben Quadinaros', height: '163', mass: '65', hair_color: 'none', skin_color: 'grey, green, yellow', eye_color: 'orange', birth_year: 'unknown', gender: 'male', homeworld_id: 41, id: 50)
Person.create(name: 'Mace Windu', height: '188', mass: '84', hair_color: 'none', skin_color: 'dark', eye_color: 'brown', birth_year: '72BBY', gender: 'male', homeworld_id: 42, id: 51)
Person.create(name: 'Ki-Adi-Mundi', height: '198', mass: '82', hair_color: 'white', skin_color: 'pale', eye_color: 'yellow', birth_year: '92BBY', gender: 'male', homeworld_id: 43, id: 52)
Person.create(name: 'Kit Fisto', height: '196', mass: '87', hair_color: 'none', skin_color: 'green', eye_color: 'black', birth_year: 'unknown', gender: 'male', homeworld_id: 44, id: 53)
Person.create(name: 'Eeth Koth', height: '171', mass: 'unknown', hair_color: 'black', skin_color: 'brown', eye_color: 'brown', birth_year: 'unknown', gender: 'male', homeworld_id: 45, id: 54)
Person.create(name: 'Adi Gallia', height: '184', mass: '50', hair_color: 'none', skin_color: 'dark', eye_color: 'blue', birth_year: 'unknown', gender: 'female', homeworld_id: 9, id: 55)
Person.create(name: 'Saesee Tiin', height: '188', mass: 'unknown', hair_color: 'none', skin_color: 'pale', eye_color: 'orange', birth_year: 'unknown', gender: 'male', homeworld_id: 47, id: 56)
Person.create(name: 'Yarael Poof', height: '264', mass: 'unknown', hair_color: 'none', skin_color: 'white', eye_color: 'yellow', birth_year: 'unknown', gender: 'male', homeworld_id: 48, id: 57)
Person.create(name: 'Plo Koon', height: '188', mass: '80', hair_color: 'none', skin_color: 'orange', eye_color: 'black', birth_year: '22BBY', gender: 'male', homeworld_id: 49, id: 58)
Person.create(name: 'Mas Amedda', height: '196', mass: 'unknown', hair_color: 'none', skin_color: 'blue', eye_color: 'blue', birth_year: 'unknown', gender: 'male', homeworld_id: 50, id: 59)
Person.create(name: 'Gregar Typho', height: '185', mass: '85', hair_color: 'black', skin_color: 'dark', eye_color: 'brown', birth_year: 'unknown', gender: 'male', homeworld_id: 8, id: 60)
Person.create(name: 'Cordé', height: '157', mass: 'unknown', hair_color: 'brown', skin_color: 'light', eye_color: 'brown', birth_year: 'unknown', gender: 'female', homeworld_id: 8, id: 61)

Person.create(name: 'Cliegg Lars', height: '183', mass: 'unknown', hair_color: 'brown', skin_color: 'fair', eye_color: 'blue', birth_year: '82BBY', gender: 'male', homeworld_id: 1, id: 62)
Person.create(name: 'Poggle the Lesser', height: '183', mass: '80', hair_color: 'none', skin_color: 'green', eye_color: 'yellow', birth_year: 'unknown', gender: 'male', homeworld_id: 11, id: 63)
Person.create(name: 'Luminara Unduli', height: '170', mass: '56.2', hair_color: 'black', skin_color: 'yellow', eye_color: 'blue', birth_year: '58BBY', gender: 'female', homeworld_id: 51, id: 64)
Person.create(name: 'Barriss Offee', height: '166', mass: '50', hair_color: 'black', skin_color: 'yellow', eye_color: 'blue', birth_year: '40BBY', gender: 'female', homeworld_id: 51, id: 65)
Person.create(name: 'Dormé', height: '165', mass: 'unknown', hair_color: 'brown', skin_color: 'light', eye_color: 'brown', birth_year: 'unknown', gender: 'female', homeworld_id: 8, id: 66)
Person.create(name: 'Dooku', height: '193', mass: '80', hair_color: 'white', skin_color: 'fair', eye_color: 'brown', birth_year: '102BBY', gender: 'male', homeworld_id: 52, id: 67)
Person.create(name: 'Bail Prestor Organa', height: '191', mass: 'unknown', hair_color: 'black', skin_color: 'tan', eye_color: 'brown', birth_year: '67BBY', gender: 'male', homeworld_id: 2, id: 68)
Person.create(name: 'Jango Fett', height: '183', mass: '79', hair_color: 'black', skin_color: 'tan', eye_color: 'brown', birth_year: '66BBY', gender: 'male', homeworld_id: 53, id: 69)
Person.create(name: 'Zam Wesell', height: '168', mass: '55', hair_color: 'blonde', skin_color: 'fair, green, yellow', eye_color: 'yellow', birth_year: 'unknown', gender: 'female', homeworld_id: 54, id: 70)
Person.create(name: 'Dexter Jettster', height: '198', mass: '102', hair_color: 'none', skin_color: 'brown', eye_color: 'yellow', birth_year: 'unknown', gender: 'male', homeworld_id: 55, id: 71)
Person.create(name: 'Lama Su', height: '229', mass: '88', hair_color: 'none', skin_color: 'grey', eye_color: 'black', birth_year: 'unknown', gender: 'male', homeworld_id: 10, id: 72)
Person.create(name: 'Taun We', height: '213', mass: 'unknown', hair_color: 'none', skin_color: 'grey', eye_color: 'black', birth_year: 'unknown', gender: 'female', homeworld_id: 10, id: 73)
Person.create(name: 'Jocasta Nu', height: '167', mass: 'unknown', hair_color: 'white', skin_color: 'fair', eye_color: 'blue', birth_year: 'unknown', gender: 'female', homeworld_id: 9, id: 74)
Person.create(name: 'R4-P17', height: '96', mass: 'unknown', hair_color: 'none', skin_color: 'silver, red', eye_color: 'red, blue', birth_year: 'unknown', gender: 'female', homeworld_id: 28, id: 75)
Person.create(name: 'Wat Tambor', height: '193', mass: '48', hair_color: 'none', skin_color: 'green, grey', eye_color: 'unknown', birth_year: 'unknown', gender: 'male', homeworld_id: 56, id: 76)
Person.create(name: 'San Hill', height: '191', mass: 'unknown', hair_color: 'none', skin_color: 'grey', eye_color: 'gold', birth_year: 'unknown', gender: 'male', homeworld_id: 57, id: 77)
Person.create(name: 'Shaak Ti', height: '178', mass: '57', hair_color: 'none', skin_color: 'red, blue, white', eye_color: 'black', birth_year: 'unknown', gender: 'female', homeworld_id: 58, id: 78)
Person.create(name: 'Grievous', height: '216', mass: '159', hair_color: 'none', skin_color: 'brown, white', eye_color: 'green, yellow', birth_year: 'unknown', gender: 'male', homeworld_id: 59, id: 79)
Person.create(name: 'Tarfful', height: '234', mass: '136', hair_color: 'brown', skin_color: 'brown', eye_color: 'blue', birth_year: 'unknown', gender: 'male', homeworld_id: 14, id: 80)
Person.create(name: 'Raymus Antilles', height: '188', mass: '79', hair_color: 'brown', skin_color: 'light', eye_color: 'brown', birth_year: 'unknown', gender: 'male', homeworld_id: 2, id: 81)
Person.create(name: 'Sly Moore', height: '178', mass: '48', hair_color: 'none', skin_color: 'pale', eye_color: 'white', birth_year: 'unknown', gender: 'female', homeworld_id: 60, id: 82)
Person.create(name: 'Tion Medon', height: '206', mass: '80', hair_color: 'none', skin_color: 'grey', eye_color: 'black', birth_year: 'unknown', gender: 'male', homeworld_id: 12, id: 83)

p "Created #{Person.count} people"
